### ISSUE TITLE
Explore efficient in-project module sharing for CMake Project

### ISSUE THREAD

**Issue by ggfan** [android/ndk-samples#520]
To Capture & carry-on the discussion for sharing CMake sub-project:
@DanAlbert
Maybe something like this? https://gitlab.kitware.com/cmake/community/wikis/doc/tutorials/Exporting-and-Importing-Targets

  @ggfan
ggfan 34 minutes ago  Member
this is built it into a third party lib, and then import it as an external lib. Which essentially is what cdep is ( and CDep goes one step further: release the binary, not source so no need to build at all)

  @gpx1000
gpx1000 17 minutes ago
@DanAlbert That is an awesome idea. However, I'm noticing that there's a requirement there of an "install" phase for CMake. FWIW as far as I know, Android Studio's gradle plugin doesn't utilize the cmake install phase; only build.

However, the interesting thing about this as an idea is if, in the future, there were to be a cmake install phase available, then we can use CPack or any form of exporting/importing targets or even targeting non-android builds. It would eliminate many of the requirements from other systems. It also would mean that we could craft a CPack CDep package generator and eliminate the need for a separate gradle publishing plugin.

**Comment by ggfan** [comment]
closing this for now to focus on content issues, then come back to it

**Comment by DanAlbert** [comment]
Why not keep it open so we don't forget about it?

**Comment by ggfan** [comment]
it is ongoing things for all of the time, not need to keep it open there on the top but not actually that top on priority

**Comment by DanAlbert** [comment]
Use a milestone? Or a label? There's no way to find the "closed but not fixed" bugs like this.

**Comment by gpx1000** [comment]
FWIW, there is another design pattern that's worth mentioning when dealing with cmake dependencies.  I personally still favor adding an install phase to the gradle plugin as it opens a lot of functionality up.  However, this is something that is equally worth mentioning.

For quite awhile, we've had access to ExternalProject_add() and that family of CMake operations.  I never really favored using it due to the way it's used.  During the configuration phase of CMake, ExternalProject_add will tell CMake that it needs to download(resolve) a target.  The build phase will then download it, and finally after the project is created, the make phase will build it.

This has led to a lot of fun hacky solutions like super externalproject generation and is counter to the target style philosophy of how to do CMake.  Thus, despite that functionality being available within the CMake version that the NDK ships with, it's not worth mentioning here.

However, CMake 3.11 added a new module that is worth mentioning here.  FetchContent.  The reason why it's significant is it does the download during the configuration stage.  Thus if you have a dependency that is shared, you can depend upon CMake to do the right thing for you by doing this:
```
include(FetchContent)
FetchContent_Declare(
    googletest
    GIT_REPOSITORY https://github.com/google/googletest.git
    GIT_TAG        release-1.8.0
)

FetchContent_GetProperties(googletest)
if(NOT googletest_POPULATED)
    FetchContent_Populate(googletest)
    add_subdirectory(${googletest_SOURCE_DIR} ${googletest_BINARY_DIR})
endif()
```

NB: this also works with local directories.  While doing this pattern isn't a silver bullet, and doesn't solve all cases.  It is note worthy in my opinion when it comes to problems like this original bug sought to solve.
p.s. if anyone wishes to play around with this, you can either use a system CMake that is at least 3.11, or you can grab FetchContent.cmake and the template in the folder FetchContent from here:
https://github.com/Kitware/CMake/tree/master/Modules . Then add that to your local modules list like so:
`list(APPEND CMAKE_MODULE_PATH ${CMAKE_CURRENT_SOURCE_DIR}/cmake/Modules)`

**Comment by gpx1000** [comment]
Oh I should mention that what this would do is to go grab the content, place it in the binary build folder, then set lcname_SOURCE_DIR, lcname_BINARY_DIR and the lcname_POPULATED boolean during the configure cmake phase.  Thus when add_subdirectory is called, cmake is still in the configuration phase and can generate all the targets in that dependency making them useful for the rest of the project.
So in the above, any target that gtest's CMakeLists.txt defines is now available for any target currently being worked on i.e. link_libraries( foo gtest::gmock ) or something similar would correctly set the include directories / and library to link against.

**Comment by ggfan** [comment]
@gpx1000, thank you for the tips, will study it ( 3.3 or 3.4 would require 3.11 as minimum CMake version, that would be the nature time to switch in )

**Comment by gpx1000** [comment]
Happy to help, lemme know if you need any more suggestions or if you need a sample.
