### ISSUE TITLE
help ! javah build c++ header file have error .

### ISSUE THREAD

**Issue by JoinBelieve** [android/ndk-samples#653]
![图片](https://user-images.githubusercontent.com/29223055/64085485-b1ce7780-cd65-11e9-932a-2243dbc5f04e.png)

I use [javah -d] cmd build header file , but it is error .  How to solve

**Comment by ggfan** [comment]
probably ndk is not configured or downloaded: jni.h header is not found.

you might go over [the doc](https://developer.android.com/studio/projects/add-native-code), then copy your header over into your template project.   otherwise, you might look at your build.gradle files in your projects and configure them correctly [ make sure you downloaded  ndk ]
