### ISSUE TITLE
dlopen failed, tries to open PC file, not Android file

### ISSUE THREAD

**Issue by pbienst** [android/ndk-samples#669]
It seems I'm having a similar issue to https://github.com/android/ndk-samples/issues/364, which is now closed and where the workaround doesn't seem to help for me.

I'm trying to link to Python 3.7 downloaded using the instructions from here: https://github.com/codelv/conda-mobile

I added this to cpp\CMakeLists.txt:

```
# add libpython
add_library(lib_python3.7m SHARED IMPORTED)
set_target_properties(lib_python3.7m PROPERTIES IMPORTED_LOCATION
        ${distribution_DIR}/conda-android-python/lib/${ANDROID_ABI}/libpython3.7m.so)

# workaround from https://github.com/android/ndk-samples/issues/364, does not work...
#set(CMAKE_C_FLAGS "${CMAKE_C_FLAGS} -L$${distribution_DIR}/conda-android-python/lib/${ANDROID_ABI}")
#set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -L${distribution_DIR}/conda-android-python/lib/${ANDROID_ABI}")

# build pybridge
add_library(pybridge SHARED
        pybridge.c)

target_include_directories(pybridge PRIVATE
        ${distribution_DIR}/conda-android-python/include/${ANDROID_ABI})

target_link_libraries(pybridge
        android
        lib_python3.7m
        log)
```

build.gradle (Module: app) has:

```
sourceSets {
        main {
            // let gradle pack the shared library into apk
            jniLibs.srcDirs = ['../distribution/gperf/lib',
                               '../distribution/conda-android-python/lib']
        }
    }
```

Compiling and linking works fine, but this the error I get:

```
java.lang.UnsatisfiedLinkError: dlopen failed: library "D:/cygwin64/home/Peter/src/ndk-samples/hello-libs/app/src/main/cpp/../../../../distribution/conda-android-python/lib/x86/libpython3.7m.so" not found
        at java.lang.Runtime.loadLibrary0(Runtime.java:1071)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1007)
        at java.lang.System.loadLibrary(System.java:1667)
        at com.example.hellolibs.MainActivity.<clinit>(MainActivity.java:37)
        at java.lang.Class.newInstance(Native Method)
```

As far as I can tell, the emulator should not try to open a file on the host OS...

Running Android Studio 3.5.2, Gradle 5.4.1

**Comment by ggfan** [comment]
does not seem to be simple download and use the lib. It is interesting ( but we do not support python for Android, you are welcome to make it to work ). 

for this particular issue, if you upload the things, and related pre-built libs,  probably would save some time.  Otherwise, you will need to check if you have the libpuython3.7.so inside your APK/Bundle  (whatever you use ), and check your loading lib code in your java code.

**Comment by pbienst** [comment]
I load the library with        
```
System.loadLibrary("pybridge");
```

The library is in the APK:

![Annotation 2019-12-08 110016](https://user-images.githubusercontent.com/2807332/70387832-3d315780-19aa-11ea-832c-75a4b5779efa.png)


Code and binaries can be found here:
https://www.dropbox.com/s/ekajyfzwu7cgv0o/hello-libs.zip?dl=0

Thanks for looking into this!

**Comment by ggfan** [comment]
acknowledged, thank you for the code. I saw it will follow-up with it, you would also see it is embedded inside the lib:
$sdk/ndk-bundle/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android-readelf -d libpybridge.so  

Dynamic section at offset 0x7b98 contains 29 entries:
  Tag        Type                         Name/Value
 0x0000000000000001 (NEEDED)             Shared library: [libandroid.so]
 0x0000000000000001 (NEEDED)             Shared library: [/usr/local/google/home/gfan/proj/debug/hello-libs/app/src/main/cpp/../../../../distribution/conda-android-python/lib/arm64-v8a/libpython3.7m.so]

**Comment by pbienst** [comment]
Sorry, I couldn't quite understand your last comment. Is there something you want me to do?

**Comment by rprichard** [comment]
The libpybridge.so library has these DT_NEEDED/DT_SONAME entries:
```
~/Downloads/hello-libs$ /x/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android-readelf -d ./app/build/intermediates/cmake/debug/obj/armeabi-v7a/libpybridge.so | grep 'NEEDED\|SONAME'
 0x00000001 (NEEDED)                     Shared library: [libandroid.so]
 0x00000001 (NEEDED)                     Shared library: [D:/cygwin64/home/Peter/src/ndk-samples/hello-libs/app/src/main/cpp/../../../../distribution/conda-android-python/lib/armeabi-v7a/libpython3.7m.so]
 0x00000001 (NEEDED)                     Shared library: [liblog.so]
 0x00000001 (NEEDED)                     Shared library: [libm.so]
 0x00000001 (NEEDED)                     Shared library: [libdl.so]
 0x00000001 (NEEDED)                     Shared library: [libc.so]
 0x0000000e (SONAME)                     Library soname: [libpybridge.so]
```

Because the DT_NEEDED entry is `D:/cygwin64/home/Peter/src/ndk-samples/hello-libs/app/src/main/cpp/../../../../distribution/conda-android-python/lib/armeabi-v7a/libpython3.7m.so`, the Android dynamic linker will search for this host path and won't find anything. Instead, this DT_NEEDED entry should just be `libpython3.7m.so`.

I'm guessing CMake is passing the absolute host path for `libpython3.7m.so` to the linker when linking `libpybridge.so`, so the absolute path is embedded into `libpybridge.so`. `libpython3.7m.so` doesn't have a DT_SONAME set, but if it did have one, then the linker would use the DT_SONAME rather than the absolute path.

```
~/Downloads/hello-libs$ /x/android-ndk-r20/toolchains/llvm/prebuilt/linux-x86_64/bin/aarch64-linux-android-readelf -d ./distribution/conda-android-python/lib/armeabi-v7a/libpython3.7m.so | grep SONAME
<nothing is output>
```

I think the NDK's build systems try to pass `-Wl,-soname,<name>` when linking a shared object, which sets the DT_SONAME. In this case, I think it'd make sense to link `libpython3.7m.so` with `-Wl,-soname,libpython3.7m.so`.

If we can't set the soname on `libpython3.7m.so`, then maybe when CMake links `libpybridge.so`, it could specify the path to `libpython3.7m.so` using `-lpython3.7m -L<path to library>`?

**Comment by ggfan** [comment]
Following rprichard's suggestion of building libpybridge.so, it could be built with:
```java
# build pybridge
add_library(pybridge SHARED  pybridge.c)
target_include_directories(pybridge PRIVATE  ${distribution_DIR}/conda-android-python/include/${ANDROID_ABI})
target_compile_options(pybridge PRIVATE -Wno-unused-value)
target_link_libraries(pybridge
        android
        log
        -lpython3.7m -L${distribution_DIR}/conda-android-python/lib/${ANDROID_ABI}
        )
```
you could try it out on your end, @pbienst . 

In terms of the @rprichard's first suggestion which fixes the problem at the "root", you may contact the libpython3.7m.so owner to compile with the given flag, so no one will have trouble anymore.

**Comment by pbienst** [comment]
Seems to have worked, thanks! I'll contact the libpython owner too.
