### ISSUE TITLE
If the demo nn-sample can only run by Android Studio 4.0?

### ISSUE THREAD

**Issue by qqchenjian318** [android/ndk-samples#721]

**Comment by qqchenjian318** [comment]
How can I use NeuralNetworks apis in my app ? My Android Studio version is 3.6.1 ,buildToolsVersion is 28.0.3? the nn-sample build config is ： compileSdkVersion 'android-R'
    buildToolsVersion '30.0.0 rc2'
    ndkVersion '21.1.6363665'，Can I use a normal version to run the demo

**Comment by ggfan** [comment]
[basic](https://github.com/android/ndk-samples/tree/master/nn-samples/basic) could be complied with NDK version r16b+, run on API level 27+ ( Android O MR1)
[sequence](https://github.com/android/ndk-samples/tree/master/nn-samples/sequence) must be compiled with 21.1+, run on API level 30+(right now is R preview ), because those new features are only in Android 11 and above.

Studio version does not matter, just the NDK version. Refer to [wiki page](https://github.com/android/ndk-samples/wiki/Configure-NDK-Path) to configure NDK in gradle and your local system.
