### ISSUE TITLE
curl-ssl sample gradle sync error in android studio 4.1

### ISSUE THREAD

**Issue by howardpang** [android/ndk-samples#753]
Task :prepareKotlinBuildScriptModel UP-TO-DATE
/Users/xxx/Downloads/curl-ssl/app/src/main/cpp/CMakeLists.txt : C/C++ debug|x86 : CMake Error at /Users/xxx/Downloads/curl-ssl/app/src/main/cpp/CMakeLists.txt:20 (find_package):
  Could not find a package configuration file provided by "curl" with any of
  the following names:

    curlConfig.cmake
    curl-config.cmake

  Add the installation prefix of "curl" to CMAKE_PREFIX_PATH or set
  "curl_DIR" to a directory containing one of the above files.  If "curl"
  provides a separate development package or SDK, be sure it has been
  installed.

/Users/xxx/Downloads/curl-ssl/app/src/main/cpp/CMakeLists.txt : C/C++ debug|x86 : Configuration failed.
executing external native build for cmake /Users/xxx/Downloads/curl-ssl/app/src/main/cpp/CMakeLists.txt

android studio 4.1
android gradle plugin 4.1

**Comment by ggfan** [comment]
it works for me on Mac. One change between 4.0 and 4.1 is the way to enable prefab in gradle:
  - AGP 4.0:  file gradle.properties, with `android.enablePrefab=true`
  - AGP 4.1:  app/build.gradle, with ` android { buildfeatures.prefab=true }`

so you need to change that after you update build script to 4.1.  Otherwise you get an error message saying the former way does not work anymore.  It is in the [doc](https://developer.android.com/studio/build/native-dependencies?buildsystem=cmake&agpversion=4.1#build_system_configuration). 

If yours still does not work, put more details about your environment, we could look further ( as we are looking at this topic now )

**Comment by howardpang** [comment]
it work after adding `buildFeatures { prefab = true } ` to app/build.gradle; The android gradle plugin doc didn't specify it
[https://developer.android.com/studio/releases/gradle-plugin?buildsystem=cmake#configure-external-build](url)
