### ISSUE TITLE
nnapi basic sample seems to fail to query supported ops from devices

### ISSUE THREAD

**Issue by zhoonit** [android/ndk-samples#767]
`nnapi/basic` example seems to fail to get supported ops from devices.

I tried to run `nnapi/basic samples` and I run into the error below while `nnapi/seqence` example runs fine without an error.

```
E/VersionedInterfaces: getSupportedOperations_1_3 failure: Status(EX_TRANSACTION_FAILED): 'FAILED_TRANSACTION: '
E/Manager: IDevice::getSupportedOperations returned the error GENERAL_FAILURE
```

AFAIK, the implementaion of `IDevice::getSupportedOperations` is device specific so I tried to query the available deivces with feature level to check if there is any, 2. tried with virtual device as well. However, the sample app ran into the same error.

My current setup is..

OS: x86 windows 10
Android studio 4.0 on a master commit of this repository(98a82c2)

First try was on SM-G986N (Galaxy s20+ with Qualcomm Snapdragon 865)
Second try was on Pixel_3a_API_30 (default virtual device came up with the new android studio 4.0)

I queried [available devices with feature level](https://github.com/zhoonit/ndk-samples/commit/2a1dac2c913f132031dd3f1ef17a1fb8b583a062)

The first try one got:
```
I/NNAPI_BASIC: device name: qti-default, supported feature level 29
    device name: qti-dsp, supported feature level 29
    device name: qti-gpu, supported feature level 29
    device name: qti-hta, supported feature level 29
    device name: nnapi-reference, supported feature level 10000
```

and the second one got:
```
I/NNAPI_BASIC: device name: nnapi-sample_all, supported feature level 30
    device name: nnapi-sample_float_fast, supported feature level 30
    device name: nnapi-sample_float_slow, supported feature level 30
    device name: nnapi-sample_minimal, supported feature level 30
    device name: nnapi-sample_quant, supported feature level 30
    device name: nnapi-reference, supported feature level 10000
```

Available devices are different but what you would get is the same on both devices.. (while in a call `ANeuralNetworksCompilation_finish`)

I reckon because they are falling back to a cpu implementation, they are working fine in terms of functionality but they are not delegated to use any acceleration.

I think reproducing the issue can be done by freshly installed android studio 4.0 and trying on a virtual device.
I am reporting the issue because `sequence` example had no such errors.

I'd like to know possible cause of the error and how to resolve those.

Thank you in advance for your kind help :)

**Comment by iwatake2222** [comment]
I met exactly the same error and found the solution. I use NNAPI from TensorFlow Lite NNAPI delegate, so it may not work in your case, though.

```
E/VersionedInterfaces: getSupportedOperations_1_3 failure: Status(EX_TRANSACTION_FAILED): 'FAILED_TRANSACTION: '
E/Manager: IDevice::getSupportedOperations returned the error GENERAL_FAILURE
```

In my case, changing the way to load model was the solution.
 - before: load my model from external storage
 - after: load my model from buffer

At first, I loaded my model from external storage. My app has the permission to access it, so loading the model and using the model from TensorFlowLite succeeded.
However, when `getSupportedOperations` accesses the model the error happened. I modified my code to read the model file to temporal buffer, then load the model from the buffer. Then, the error disappeared.
It looks `getSupportedOperations` has different permission from the app.

I'm not sure if NNAPI offers API to load a model from buffer. Also, `model_data.bin` (<- I guess this is a model for NNAPI)  is stored in assets directory (not in external storage). Still, I think it might be a good idea to check access permission.

**Comment by Kottsone** [comment]
Thanks for reporting this issue. 

This is because the NNAPI drivers do not have the permission of assessing asset files on some devices. We will fix this permission issue in future Android releases. For devices with earlier Android version, as @iwatake2222 suggested, please load the model from a buffer instead:

1. Use `ASharedMemory_create` to allocate a large-enough shared memory to hold model data
2. Use `AAsset_read` to load the content of the asset file to the shared memory
3. Use `ANeuralNetworksMemory_createFromFd` to create a NNAPI memory object with the shared memory fd

We will also modify the `basic` sample to demonstrate this process.

**Comment by enduringstack** [comment]
@Kottsone  Which NNAPI cause the issue?

**Comment by Kottsone** [comment]
@enduringstack Do you mean which NNAPI _driver_ causes the issue?

This issue is not specific to any NNAPI driver. All NNAPI drivers (expect for nnapi-reference) may not have the correct permission to access asset files, depending on the SELinux policy configuration on the device. So my recommendation would be to always load model data from a shared memory at API level 30 or earlier.

**Comment by ggfan** [comment]
With https://github.com/android/ndk-samples/pull/804 merged, this is resolved; please kindly double check it and reopen if the issue still exists. Thank you!
