### ISSUE TITLE
Project structure for c/c++ files

### ISSUE THREAD

**Issue by estobbart** [android/ndk-samples#856]
The [Projects Structure](https://developer.android.com/studio/projects) doc uses a main/jni directory for the c/c++ code. The projects here use a main/cpp directory. Is one or the other correct, or out of date?
It just didn't feel good to be putting my c code in a cpp directory 🤷‍♂️ .

**Comment by ggfan** [comment]
it is just a name, does not mean it should be only C++ files. The chain to find C/C++ file to compile is:
- [C/C++ build script file with path in the build.gradle file](https://github.com/android/ndk-samples/blob/main/hello-jni/app/build.gradle#L28)
- [individual C/C++ file with path in the C/C++ build script file](https://github.com/android/ndk-samples/blob/main/hello-jni/app/src/main/cpp/CMakeLists.txt#L4)

Gradle (Android Gradle Plugin) does not default to any directory name.  ndk-build command line tool takes jni as the default directory to build, but you can use the `ndk-build -C` to change to your own directory. 

Historically, it was `jni`,  then along the way some kind of motion for `cpp` so you will write more cpp code rather than c code; on the other hand, I think that all ndk APIs are C interface only (so you will have to deal with C once you want register any callbacks to NDK APIs, but it is in the limited scope). 

Probably just make your favorite choice and configure your build script accordingly, it will just work out fine. If you are porting code from other platforms, just change the build script files so your source could stay in a place sharable to all OSes.

**Comment by estobbart** [comment]
Do you know if Android Studio has a preference? It seems if you are starting a new native module from scratch that it also uses the cpp directory. The project is using CMake.

Thank you for this.

**Comment by ggfan** [comment]
Studio by default creates project with "cpp" directory and have that path in the module's build.gradle (app/build.gradle) file, that is from the template.  That is all it is: no other places in the build scripts hardcode to "cpp" or "jni": it is a configuration thing. 

It is true that Studio (mainly Android Gradle Plugin) uses "cpp", ndk-build defaults to "jni".  But they are all one time configuration thing.
